# Generated by Django 3.2.18 on 2023-05-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
