# Generated by Django 3.2.18 on 2023-05-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230524_1000'),
        ('accounts', '0003_remove_user_nickname'),
    ]

    operations = [
    ]
